# Generated by Django 4.2.3 on 2023-07-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
    ]
