# Generated by Django 4.2.3 on 2023-07-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(default="", max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=60),
        ),
    ]
