# Generated by Django 4.2.3 on 2023-07-10 02:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_img",
            field=models.ImageField(
                default="default/no_image.png",
                upload_to=users.models.CustomUser.image_upload_to,
            ),
        ),
    ]
