# Generated by Django 4.2.3 on 2023-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_img",
            field=models.ImageField(default="img/no_image.png", upload_to="img/"),
        ),
    ]
