# Generated by Django 4.2.3 on 2023-07-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(default="no_image.png", upload_to="profile_images"),
        ),
    ]
