# Generated by Django 4.2.3 on 2023-07-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_profile_description_remove_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_img",
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(default="no_image.png", upload_to="profile_images"),
        ),
    ]
