# Generated by Django 4.2.3 on 2023-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_customuser_profile_img_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="", max_length=40),
        ),
    ]
