# Generated by Django 4.2.3 on 2023-07-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
