# Generated by Django 4.2.3 on 2023-07-14 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_profile_bio_profile_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="description",
            new_name="bio",
        ),
    ]
