# Generated by Django 4.2.3 on 2023-07-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_description_customuser_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
    ]
