# Generated by Django 4.2.3 on 2023-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
