# Generated by Django 4.2.3 on 2023-07-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(default="", max_length=101),
        ),
    ]
