# Generated by Django 4.2.3 on 2023-07-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="website",
            field=models.URLField(default="", max_length=250),
        ),
    ]
